version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.0

jobs:
  build:
    executor:
      name: android/android-machine
    steps:
      - checkout
      - flutter/install_sdk_and_pub:
          version: stable
      - flutter/install_android_gradle_dependencies
      - flutter/install_android_gem

      - run:
          name: Flutter pub get
          command: |
            flutter pub get

      - run:
          name: Build APK
          command: |
            flutter build apk --release

      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk
