# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
  android: circleci/android@1.0.3
  flutter: circleci/flutter@2.0.0
  slack: circleci/slack@4.1

workflows:
  send-notification:
     jobs:
      - notify:
          context: slack-secrets

jobs:
  build:
    docker: 
      - image: instrumentisto/flutter
      - image: cimg/base:stable
    steps:
      - checkout
      - run: 
          name: Build Flutter (Android)
          command: |
            flutter build apk --release
      - store_artifacts:
          path: build/app/outputs/flutter-apk/app-release.apk\
      - slack/notify:
          custom: |
            {
              "blocks": [
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "plain_text",
                      "text": "*This is a text notification*",
                      "emoji": true
                    }
                  ]
                }
              ]
            }
          event: always