// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjAhhAjOGs4yyWIvWqEFM53bbRLW9ylZo',
    appId: '1:551362532286:web:dad6c76bcbb53f9687dfef',
    messagingSenderId: '551362532286',
    projectId: 'cryptonance-c6342',
    authDomain: 'cryptonance-c6342.firebaseapp.com',
    storageBucket: 'cryptonance-c6342.appspot.com',
    measurementId: 'G-KTE0FCVKFJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcruEXeei878l9z_b5juZKfkbgo1AwEQs',
    appId: '1:551362532286:android:18d6c8c1ef61abff87dfef',
    messagingSenderId: '551362532286',
    projectId: 'cryptonance-c6342',
    storageBucket: 'cryptonance-c6342.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCvwbB66u7A4h2TXWm8mB6mArKV4UyjLh0',
    appId: '1:551362532286:ios:c438c7dccde46b4187dfef',
    messagingSenderId: '551362532286',
    projectId: 'cryptonance-c6342',
    storageBucket: 'cryptonance-c6342.appspot.com',
    iosBundleId: 'com.example.cryptonance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCvwbB66u7A4h2TXWm8mB6mArKV4UyjLh0',
    appId: '1:551362532286:ios:f81b989e1e16b19287dfef',
    messagingSenderId: '551362532286',
    projectId: 'cryptonance-c6342',
    storageBucket: 'cryptonance-c6342.appspot.com',
    iosBundleId: 'com.example.cryptonance.RunnerTests',
  );
}
