on:
  push: 
    branches:
      - master-getx

name: cryptonance

jobs:
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - run: flutter pub get 
      - run: flutter build apk ---release 
      
      - name: Push to Release 
        uses: ncipollo/release-action@v1
        with: 
          artifacs: "build/app/outputs/apk/flutter-apk/*"
          tag: v0.0.1
          token: ${{secrets.TOKEN}}
